apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolfined
   labels:
     env: prod
spec: 
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx
