apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolfined
spec: 
  replicas: 4
  selector:
    matchLabels:
      env: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadaa:
      labels:
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx
