apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dolfined
spec: # replicas, selectors, pod template
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx
